name: proyecto_f1kedro

services:
  postgres:
    image: postgres:15
    container_name: f1_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 20

  airflow-init:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: f1_airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: /bin/bash
    command:
      - -lc
      - |
        set -e
        airflow db migrate
        airflow users list | grep -q "^admin\s" || airflow users create \
          --username "${_AIRFLOW_WWW_USER_USERNAME}" \
          --password "${_AIRFLOW_WWW_USER_PASSWORD}" \
          --firstname "${_AIRFLOW_WWW_USER_FIRSTNAME}" \
          --lastname "${_AIRFLOW_WWW_USER_LASTNAME}" \
          --role Admin \
          --email "${_AIRFLOW_WWW_USER_EMAIL}"
        echo "Airflow init OK"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 07b5ca48823f0221b105351631e96f204c9f7ba29b64ce5f24a6eae01c74693d
      AIRFLOW__CORE__FERNET_KEY: nrtA53yWGOFp99gZxAJyVm3jDDo7nT6Czi0z6LvHpbs=
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      _AIRFLOW_WWW_USER_FIRSTNAME: Admin
      _AIRFLOW_WWW_USER_LASTNAME: User
      _AIRFLOW_WWW_USER_EMAIL: admin@example.com
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: f1_airflow_webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    command: ["webserver"]
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 07b5ca48823f0221b105351631e96f204c9f7ba29b64ce5f24a6eae01c74693d
      AIRFLOW__CORE__FERNET_KEY: nrtA53yWGOFp99gZxAJyVm3jDDo7nT6Czi0z6LvHpbs=
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: f1_airflow_scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    command: ["scheduler"]
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 07b5ca48823f0221b105351631e96f204c9f7ba29b64ce5f24a6eae01c74693d
      AIRFLOW__CORE__FERNET_KEY: nrtA53yWGOFp99gZxAJyVm3jDDo7nT6Czi0z6LvHpbs=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project

  jupyter:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: f1_jupyter
    command: >
      bash -lc "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser
      --NotebookApp.token='' --NotebookApp.password='' --allow-root"
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace

  kedro-viz:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: f1_kedro_viz
    working_dir: /workspace
    command: ["bash", "-lc", "kedro viz run --host 0.0.0.0 --port 4141 --no-browser"]
    ports:
      - "4141:4141"
    volumes:
      - ./:/workspace


volumes:
  postgres_data:
